ALTER TABLE public."PhysicalAssessment"
  ADD COLUMN IF NOT EXISTS "sex" TEXT NULL,
  ADD COLUMN IF NOT EXISTS "age" INTEGER NULL,
  ADD COLUMN IF NOT EXISTS "waistCm" NUMERIC NULL,
  ADD COLUMN IF NOT EXISTS "neckCm" NUMERIC NULL,
  ADD COLUMN IF NOT EXISTS "hipCm" NUMERIC NULL,
  ADD COLUMN IF NOT EXISTS "bmi" NUMERIC NULL,
  ADD COLUMN IF NOT EXISTS "bmiClassification" TEXT NULL,
  ADD COLUMN IF NOT EXISTS "basalMetabolicRate" NUMERIC NULL,
  ADD COLUMN IF NOT EXISTS "calculationMethod" TEXT NULL;
